// Generated by CoffeeScript 1.7.1
(function() {
  var ucseq;

  ucseq = module.exports;

  ucseq.some = function(coll, predicate) {
    var e, r, result, _i, _len;
    result = null;
    for (_i = 0, _len = coll.length; _i < _len; _i++) {
      e = coll[_i];
      r = predicate(e);
      if (r) {
        result = r;
        break;
      }
    }
    return result;
  };

}).call(this);
